// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countItems = `-- name: CountItems :one
SELECT count(*) FROM items
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, status, created_at FROM items WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, name, status, created_at FROM items
ORDER BY created_at DESC, id ASC
LIMIT $1 OFFSET $2
`

type ListItemsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO items (id, name, status, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, status = EXCLUDED.status
`

type UpsertItemParams struct {
	ID        string
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.Exec(ctx, upsertItem,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}
