// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID        string
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
}
