// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CountItems(ctx context.Context) (int64, error)
	GetItemByID(ctx context.Context, id string) (Item, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	UpsertItem(ctx context.Context, arg UpsertItemParams) error
}

var _ Querier = (*Queries)(nil)
